; C&C World-Altering Editor (WAE)
; https://github.com/Rampastring/WorldAlteringEditor

; Specifies directories that the file manager will load MIX files from.
[SearchDirectories]
0=.
1=Map Editor

; Specifies primary MIX files. The editor will refuse to start if one of these is not found.
; Special values are supported to load additional MIX files.
; The valid options are $TSECACHE, $RA2ECACHE, $TSELOCAL, $RA2ELOCAL, $EXPAND, $EXPANDMD.
; The editor WILL start even if none of them are found.
[PrimaryMIXFiles]
0=langmd.mix
1=language.mix
2=$EXPANDMD
3=ra2md.mix
4=ra2.mix
5=cachemd.mix
6=cache.mix
7=localmd.mix
8=local.mix
9=$RA2ECACHE
10=$RA2ELOCAL
11=conqmd.mix
12=genermd.mix
13=generic.mix
14=isogenmd.mix
15=isogen.mix
16=conquer.mix

30=expandmd10.mix
31=expandmd11.mix
32=expandmd12.mix
33=expandmd13.mix
34=expandmd14.mix
35=expandmd15.mix
36=expandmd16.mix
;37=expandmd17.mix
38=expandmd18.mix
39=expandmd19.mix
40=expandmd20.mix

41=expandmd74.mix ; TODO: move out to buildings/pal mix

; Specifies secondary MIX files.
; The editor will attempt to load these, but will start even if these are missing.
[SecondaryMIXFiles]
0=marble.mix           ; borrowed from Final Alert 2

[StringTables]
0=ra2.csf
1=ra2md.csf
2=stringtable10.csf
3=stringtable11.csf
4=stringtable20.csf
5=stringtable21.csf
6=stringtable60.csf
7=stringtable61.csf
